name: harness
services:
    harness:
        ports:
            - 3000:3000
            - 3022:3022
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/harness:/data
        container_name: harness
        restart: always
        image: harness/harness